name: Compare CSV files

on:
  push:
    branches: [main]

jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find added records
        run: comm -23 ${{ secrets.GOV_UK_SPONSOR_CSV_PATH }} ${{ secrets.GOV_UK_SPONSOR_CSV_LAST_UPDATED_PATH }} > added.csv
      - name: Find deleted records
        run: grep -vFf ${{ secrets.GOV_UK_SPONSOR_CSV_LAST_UPDATED_PATH }} ${{ secrets.GOV_UK_SPONSOR_CSV_PATH }} > deleted.csv
      - name: Add and Commit Files
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "Strange Supreme"
          git config user.email "actions@github.com"
          git pull
          git add --all
          git commit -m "Comparison"
          git push
