name: Compare CSV files

on:
  push:
    branches: [main]

jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Install the csvkit package
    - name: Install csvkit
      run: |
        echo "Installing csvkit package..."
        sudo apt-get update
        sudo apt-get install csvkit
    # Find added and deleted records
    - name: Find added and deleted records
      run: |
        echo "Finding added and deleted records..."
        csvjoin --columns file1,file2 "${{ secrets.GOV_UK_SPONSOR_CSV_LAST_UPDATED_PATH }}" "${{ secrets.GOV_UK_SPONSOR_CSV_PATH }}" | csvsql --query 'SELECT * FROM stdin WHERE file2 IS NOT NULL' > added.csv
        csvsql --query 'SELECT * FROM stdin WHERE file2 IS NULL' < added.csv > deleted.csv
    # Convert added and deleted records to JSON
    - name: Convert added and deleted records to JSON
      run: |
        echo "Converting added and deleted records to JSON format with headers as properties..."
        csvjson -k added.csv > added.json
        csvjson -k deleted.csv > deleted.json
    # Check in added and deleted records to the repository
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}
    - name: Add and commit added and deleted records
      run: |
        git config user.email "action@github.com"
        git config user.name "GitHub Action"
        git add added.csv deleted.csv added.json deleted.json
        git commit -m "Added and deleted records for $(date +%Y-%m-%d)"
    - name: Push changes
      run: git push
