name: Find File Commits

on: [push]

jobs:
  find-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          paths: .
      - name: Save Output
        run: |
          last_commit_hash=$(git log -1 --format=%H -- Skilled_Worker_List.csv)
          echo "Last commit hash inside SaveOutput: $last_commit_hash"
          diff=$(git diff $last_commit_hash^ $last_commit_hash --shortstat -- Skilled_Worker_List.csv)
          echo "Git diff output: $diff"
          # Extract the number of additions and deletions
          insertions=$(echo $diff | grep -oE "([0-9]+) insertions")
          deletions=$(echo $diff | grep -oE "([0-9]+) deletions")
          echo "Addition: $additions"
          echo "Deletion: $deletions"
          # Write the additions and deletions to separate files
          echo $additions > additions.txt
          echo $deletions > deletions.txt
      - name: Add and Commit Files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "Strange Supreme"
          git config user.email "actions@github.com"
          changes=$(git diff-index --cached HEAD)
          echo "changes $changes"
          if [ -n $changes ]; then
            git add additions.txt deletions.txt
            git commit -m "Update file commit stats"
            git push
          else
            echo "Nothing to commit."
          fi
