name: Find File Commits

on: [push]

jobs:
  find-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find Last Commit Hash
        run: |
          git log -1 --format=%H -- <file_path> > last_commit_hash.txt
      - name: Save Output
        run: |
          while read -r commit_hash; do
            # Get the difference between the commit and its parent commit
            diff=$(git diff "$commit_hash"^ "$commit_hash" --shortstat -- <file_path>)
            # Extract the number of additions and deletions
            additions=$(echo "$diff" | grep -oP "(?<=\+).*(?= insertions?)")
            deletions=$(echo "$diff" | grep -oP "(?<=-).*(?= deletions?)")
            # Write the additions and deletions to separate files
            echo "$additions" > additions.txt
            echo "$deletions" > deletions.txt
          done < last_commit_hash.txt
      - name: Add and Commit Files
        run: |
          # Check if there are any staged changes
          changes=$(git diff-index --cached HEAD)
          if [ -n "$changes" ]; then
            # There are staged changes, so commit and push the files
            git add additions.txt deletions.txt
            git commit -m "Update file commit stats"
            git push
          else
            # There are no staged changes, so do nothing
            echo "Nothing to commit."
          fi
