name: Find File Commits

on: [push]

jobs:
  find-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: List Working Tree Files
        run: |
          echo "Files in working tree:"
          ls -la
      - name: Download File from Blob Storage
        uses: actions/download-artifact@v2
        with:
          name: my-file
          path: ${{ secrets.GOV_UK_SPONSOR_CSV_PATH }}
      - name: Save Output
        run: |
          echo "Saving output..."
          # Compare the downloaded file to a previous version
          diff=$(git diff HEAD --shortstat -- ${{ secrets.GOV_UK_SPONSOR_CSV_PATH }})
          # Extract the number of additions and deletions
          additions=$(echo "$diff" | grep -oP "(?<=\+).*(?= insertions?)")
          deletions=$(echo "$diff" | grep -oP "(?<=-).*(?= deletions?)")
          # Write the additions and deletions to separate files
          echo "$additions" > additions.txt
          echo "$deletions" > deletions.txt
      - name: Add and Commit Files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          changes=$(git diff-index --cached HEAD)
          if [ -n "$changes" ]; then
            git add additions.txt deletions.txt
            git commit -m "Update file commit stats"
            git push
          else
            echo "Nothing to commit."
          fi
