name: Find File Commits

on: [push]

jobs:
  find-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Update Repository
        run: |
          echo "Updating repository..."
          git pull
      - name: Find Last Commit Hash
        run: |
          echo "Finding last commit hash..."
          last_commit_hash=$(git log -1 --format=%H -- ${{ secrets.GOV_UK_SPONSOR_CSV_PATH }})
          echo "Last commit hash: $last_commit_hash"
      - name: Save Output
        run: |
          echo "Saving output..."
          diff=$(git diff "$last_commit_hash"^ "$last_commit_hash" --shortstat -- ${{ secrets.GOV_UK_SPONSOR_CSV_PATH }})
          additions=$(echo "$diff" | grep -oP "(?<=\+).*(?= insertions?)")
          deletions=$(echo "$diff" | grep -oP "(?<=-).*(?= deletions?)")
          echo "$additions" > additions.txt
          echo "$deletions" > deletions.txt
      - name: Add and Commit Files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          changes=$(git diff-index --cached HEAD)
          if [ -n "$changes" ]; then
            git add additions.txt deletions.txt
            git commit -m "Update file commit stats"
            git push
          else
            echo "Nothing to commit."
          fi
