name: Find File Commits

on: [push]

jobs:
  find-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Update Repository
        run: |
          git pull
      - name: Find Last Commit Hash
        run: |
          git log -1 --format=%H -- ${{ secrets.GOV_UK_SPONSOR_CSV_PATH }} > last_commit_hash.txt
      - name: Save Output
        run: |
          while read -r commit_hash; do
            # Get the difference between the commit and its parent commit
            diff=$(git diff "$commit_hash"^ "$commit_hash" --shortstat -- ${{ secrets.GOV_UK_SPONSOR_CSV_PATH }})
            # Extract the number of additions and deletions
            additions=$(echo "$diff" | grep -oP "(?<=\+).*(?= insertions?)")
            deletions=$(echo "$diff" | grep -oP "(?<=-).*(?= deletions?)")
            # Write the additions and deletions to separate files
            echo "$additions" > additions.txt
            echo "$deletions" > deletions.txt
          done < last_commit_hash.txt
