name: Convert to Json
on:
  workflow_dispatch:
jobs:
  sortJsonCompress:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: Install csvtojson
      run: |
        npm install -g csvtojson
    - name: Sort CSV
      run: |
        # Use awk to sort the input file based on the values in the second column,
        # using the comma as the field separator.
        # The sorted file will be saved to sorted.csv.
        awk -F, 'NR==1; NR>1 {print $0 | "sort -t, -k2,2"}' ${{ secrets.GOV_UK_SPONSOR_CSV_PATH }} > sorted.csv
    - name: Change header names
      run: |
        # Use sed to change the header names in the sorted.csv file.
        sed '1s/^/name,city,county,rating,route\n/' sorted.csv > temp.csv
        mv temp.csv sorted.csv
    - name: Convert to JSON
      run: |
        # Use csvtojson to convert the sorted.csv file to JSON.
        # The output will be saved to output.json.
        csvtojson sorted.csv > output.json
    - name: Compress JSON
      run: |
        # Use gzip to compress the output.json file.
        # The compressed file will be saved to output.json.gz.
        gzip output.json
    - name: Delete sorted CSV
      run: |
        # Delete the sorted.csv file.
        rm sorted.csv
        echo "$datetime Find Commit" > latest_Commit_timestamp.txt
    - name: Add and Commit Files
      if: always()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          git config user.name "Strange Supreme"
          git config user.email "actions@github.com"
          git pull
          git add --all
          git commit -m "Updates to CSV"
          git push
