name: Convert to Json
on:
  workflow_dispatch:
jobs:
  sortJsonCompress:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: Install csvtojson
      run: |
        npm install -g csvtojson
    - name: Change header names
      run: |
        # Use sed to change the header names in the sorted.csv file.
        awk 'NR==1{print "name,city,county,rating,route,number"} NR>1{print $0,"\"" NR-1 "\""}' ${{ secrets.GOV_UK_SPONSOR_CSV_PATH }} > output.csv
    - name: Convert to JSON
      run: |
        # Use csvtojson to convert the sorted.csv file to JSON.
        # The output will be saved to output.json.
        echo "$datetime Find Commit" > latest_Commit_timestamp.txt
        csvtojson output.csv > output.json
    - name: Compress JSON
      run: |
        # Use gzip to compress the output.json file.
        # The compressed file will be saved to output.json.gz.
        gzip -c output.json > output.json.gz
    - name: Delete output CSV
      run: |
        # Delete the output.csv file.
        # rm output.csv
       
    - name: Add and Commit Files
      if: always()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          git config user.name "Strange Supreme"
          git config user.email "actions@github.com"
          git pull
          git add output.json.gz latest_Commit_timestamp.txt
          git commit -m "Updates to CSV"
          git push
